name: action-discord
description: Sends build notifications to Discord
author: zzak
branding:
  icon: bell
  color: orange

inputs:
  webhook:
    description: Discord webhook URL (should be secrets.DISCORD_WEBHOOK maybe)
    required: true
  github-token:
    description: |
      Github Token for the Action (should be secrets.GITHUB_TOKEN)

      See:
      https://docs.github.com/en/actions/security-guides/automatic-token-authentication#example-1-passing-the-github_token-as-an-input
    required: true


runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true
        working-directory: ${{ github.action_path }}
    - name: Notify
      shell: bash
      env:
        ACTION_DISCORD_JOB_ID: ${{ github.job }}
        DISCORD_WEBHOOK: ${{ inputs.webhook }}
        BUNDLE_GEMFILE: ${{ github.action_path }}/Gemfile
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        bundle exec ruby ${{ github.action_path }}/main.rb