name: Previous Conclusion
description: Returns the conclusion of the previous workflow run
outputs:
  result:
    description: Conclusion of the previous workflow run
    value: ${{ steps.previous.outputs.result }}

runs:
  using: "composite"

  steps:
    - name: Get conclusion of last completed run
      id: previous
      shell: bash
      run: |
        path=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/actions/runs/${{ github.run_id }} | jq --raw-output .path)
        echo $path

        resp=$(gh run list -w "$path" \
          -R ${{ github.repository }} \
          --branch ${{ github.ref_name }} \
          --json databaseId,status,conclusion)
        result=$(echo $resp | jq -c '[.[] | select(.status == "completed")] | first | .conclusion')
        echo $result
        echo "result=$result" >> $GITHUB_OUTPUT