name: Notify

on:
  workflow_call:
    secrets:
      DISCORD_WEBHOOK:
        required: true
    inputs:
      result:
        type: string
        required: true
        description: Conclusion of the caller workflow

permissions:
  contents: read

jobs:
  notify_on_fail:
    name: Notify on fail
    runs-on: ubuntu-latest
    if: ${{ inputs.result == 'failure' }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Previous Conclusion
        id: previous
        uses: zzak/action-discord/.github/actions/previous@main
      - name: Setup statuses
        id: status
        run: |
          result=$(echo '{
            "previous": ${{ steps.previous.outputs.result }},
            "result": ${{ toJson(inputs.result) }}
          }' | jq --compact-output --raw-output '{
            color: (if .result == "success" then "16711680" else "65280" end),
            title: (if .previous == "success" and .result == "success" then "Passing" else (if .previous == "failure" and .result == "success" then "Fixed" else (if .previous == "failure" and .result == "failure" then "Still Failing" else "Failed" end) end) end)
          }')
          echo $result
          echo "result=$result" >> $GITHUB_OUTPUT
      - name: Notify
        uses: zzak/action-discord/.github/actions/notify@main
        with:
          color: ${{ toJson(steps.status.outputs.result).color }}
          title: ${{ toJson(steps.status.outputs.result).title }}
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

  notify_on_fixed:
    name: Notify when fixed
    runs-on: ubuntu-latest
    if: ${{ inputs.result == 'success' }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Previous Conclusion
        id: previous
        uses: zzak/action-discord/.github/actions/previous@main
      - name: Notify
        uses: zzak/action-discord/.github/actions/notify@main
        if: ${{ contains(fromJson(steps.previous.outputs.result), 'failure') }}
        with:
          color: "65280"
          title: "Fixed"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
