name: Notify

on:
  workflow_call:
    secrets:
      DISCORD_WEBHOOK:
        required: true
    inputs:
      result:
        type: string
        required: true
        description: Conclusion of the caller workflow

permissions:
  contents: read

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Previous Conclusion
        id: previous
        uses: zzak/action-discord/.github/actions/previous@main
      - name: Setup statuses
        id: status
        run: |
          color=$(echo ${{ input.result }} | jq --compact-output --raw-output --raw-input \
            '(if . == "success" then "65280" else "16711680" end)')
          echo $color
          echo "color=$color" >> $GITHUB_OUTPUT

          title=$(echo '{
            "previous": ${{ steps.previous.outputs.result }},
            "result": ${{ toJson(inputs.result) }}
          }' | jq --compact-output --raw-output \
            '(if .previous == "success" and .result == "success" then "Passing" else
              (if .previous == "failure" and .result == "success" then "Fixed" else
                (if .previous == "failure" and .result == "failure" then "Still Failing" else "Failed" end)
              end)
            end)')
          echo $title
          echo "title=$title" >> $GITHUB_OUTPUT
      - name: Notify
        uses: zzak/action-discord/.github/actions/notify@main
        with:
          color: ${{ steps.status.outputs.color }}
          title: ${{ steps.status.outputs.title }}
          webhook: ${{ secrets.DISCORD_WEBHOOK }}