name: Inline Test

on:
  push:
    branches:
      - '**'
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: ${{ matrix.type }}
    permissions:
      contents: read
      actions: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: ruby/setup-ruby@v1
      id: setup-ruby
      with:
        ruby-version: 3.2

    - name: Lint
      id: lint
      run: |
        exit 1

    - uses: zzak/action-discord@test
      if: always() && github.ref_name == 'test'
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}

  test:
    name: ${{ matrix.type }}
    permissions:
      contents: read
      actions: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { type: 'good', allow-failure: false }
          - { type: 'bad', allow-failure: true}
          - { type: 'ugly', allow-failure: false }
    env:
      type: ${{ matrix.type }}
    steps:
    - uses: actions/checkout@v3

    - uses: ruby/setup-ruby@v1
      id: setup-ruby
      with:
        ruby-version: 3.2

    - name: Test
      continue-on-error: ${{ matrix.allow-failure || false }}
      id: tests
      run: |
        if [ $type == "good" ]
        then
          echo "good"
          exit
        else
          echo $type
          exit 1
        fi

    - uses: zzak/action-discord@test
      if: always() && github.ref_name == 'test'
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}

